# -*- coding: utf-8 -*-
"""hubert-percept-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6uHZLrVmxbHfBdSITM5IpLJQnlwPlL-

Rewritten to implement the EchoVoice data pipeline described in the
manuscript (Chapter 2, Materials and Procedures):

  Stage 1 - Data Collection and Preprocessing:
      mono 16 kHz audio, energy-thresholded VAD silence trimming, and
      peak normalization to -1.0 dBFS.
  Stage 2 - Data Augmentation and Domain Adaptation (applied dynamically
      during batch training):
      - SpecAugment time/frequency masking (F = 27 channels, T = 40 steps)
        enabled natively on the HuBERT model config.
      - Stochastic pitch-shifting between -3.0 and +4.0 semitones.
      - Mixing with ambient background noise at SNR 0-15 dB.
  Stage 3+ - keep the existing HuBERT/Large + CTC fine-tuning and the
      Levenshtein WER/PER evaluation unchanged.
"""

!pip install -q transformers datasets evaluate jiwer accelerate librosa soundfile

import torch
from transformers import AutoModelForCTC, AutoProcessor

# Verify GPU availability
print(f"CUDA Available: {torch.cuda.is_available()}")

# Load HuBERT Large
model_id = "facebook/hubert-large-ls960-ft"

processor = AutoProcessor.from_pretrained(model_id)

# Manuscript Stage 1: all audio is standardized to mono 16 kHz.
TARGET_SAMPLE_RATE = 16000

model = AutoModelForCTC.from_pretrained(
    model_id,
    ctc_loss_reduction="mean",
    pad_token_id=processor.tokenizer.pad_token_id
)

# ===== Stage 2 (a): SpecAugment on the acoustic representations =====
# Manuscript: zero-mask up to F=27 consecutive frequency channels and T=40
# consecutive time steps. HuBERT applies this internally after its CNN
# feature encoder when apply_spec_augment=True. The masking is toggled off
# again for evaluation by ToggleAugmentationCallback below.
print("Enabling SpecAugment masking (F=27 freq channels, T=40 time steps)...")
model.config.apply_spec_augment = True
model.config.mask_time_length = 40     # T = max consecutive time steps masked
model.config.mask_time_prob = 0.05
model.config.mask_feature_length = 27  # F = max consecutive freq channels masked
model.config.mask_feature_prob = 0.05

print("HuBERT Large loaded successfully!")

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/datasets"

print(os.listdir(base_path))

import zipfile
import os

zip_path = "/content/drive/MyDrive/datasets/PERCEPT-GFTA.zip"
extract_path = "/content/PERCEPT-GFTA"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_path)

print("Extracted successfully!")
print("\nTop-level contents:")
print(os.listdir(extract_path))

import os

root = "/content/PERCEPT-GFTA/PERCEPT-GFTA"

print(os.listdir(root))

data_root = "/content/PERCEPT-GFTA/PERCEPT-GFTA/PERCEPT-GFTA 2.2.2py"

items = os.listdir(data_root)

print("Total items:", len(items))
print("\nFirst 30 items:")
print(items[:30])

participant_path = os.path.join(data_root, "100")

print(os.listdir(participant_path))

metadata_path = os.path.join(data_root, "100", "metadata")

print(os.listdir(metadata_path))

import os

study_codes = set()

for participant in os.listdir(data_root):
    audio_path = os.path.join(data_root, participant, "audio")

    if not os.path.isdir(audio_path):
        continue

    for filename in os.listdir(audio_path):
        if filename.endswith(".wav"):
            parts = filename.split("_")
            if len(parts) >= 2:
                study_codes.add(parts[1])

print("Study codes:")
for code in sorted(study_codes):
    print(code)

import os
import pickle

filtered_participants = []

for participant in os.listdir(data_root):
    participant_path = os.path.join(data_root, participant)
    audio_path = os.path.join(participant_path, "audio")
    metadata_path = os.path.join(participant_path, "metadata")

    if not os.path.isdir(audio_path):
        continue

    age_file = os.path.join(metadata_path, "age.pickle")

    if not os.path.exists(age_file):
        continue

    with open(age_file, "rb") as f:
        age_months = pickle.load(f)

    # BCS only + under 12 years old
    bcs_files = [
        f for f in os.listdir(audio_path)
        if f.endswith(".wav")
        and len(f.split("_")) >= 2
        and f.split("_")[1] == "BCS"
    ]

    if bcs_files and age_months < 144:
        filtered_participants.append(participant)

print("Filtered BCS participants:", len(filtered_participants))
print("Participants:", sorted(filtered_participants, key=int))

print("Participant | Age (months) | Age (years)")
print("-" * 40)

for participant in sorted(filtered_participants, key=int):
    metadata_path = os.path.join(
        data_root, participant, "metadata", "age.pickle"
    )

    with open(metadata_path, "rb") as f:
        age_months = pickle.load(f)

    age_years = age_months / 12

    print(f"{participant:11} | {age_months:12} | {age_years:.2f}")

"""#START TRAINING🚀"""

from datasets import Dataset, Audio

train_data = []

for participant in filtered_participants:
    audio_path = os.path.join(data_root, participant, "audio")

    for filename in os.listdir(audio_path):
        if not filename.endswith(".wav"):
            continue

        parts = filename.replace(".wav", "").split("_")

        if len(parts) >= 4 and parts[1] == "BCS":
            train_data.append({
                "audio": os.path.join(audio_path, filename),
                "text": parts[3],
                "participant": participant
            })

train_dataset = Dataset.from_list(train_data)

# Load audio automatically
train_dataset = train_dataset.cast_column(
    "audio",
    Audio(sampling_rate=TARGET_SAMPLE_RATE)
)

print(train_dataset)
print("\nFirst sample:")
print(train_dataset[0])

# ===== Stage 1: preprocessing constants and helpers =====
# Manuscript: 16 kHz mono audio, energy-thresholded VAD that trims leading
# and trailing non-speech silences, then peak normalization to -1.0 dBFS.
import numpy as np
import librosa
import soundfile as sf

DBFS_LEVEL = -1.0  # target peak headroom, -1.0 dBFS
VAD_DB_THRESHOLD = -35.0  # RMS below this is treated as silence
VAD_FRAME_MS = 20.0
VAD_HOP_MS = 10.0
VAD_MIN_PAD_S = 0.05


def vad_trim(waveform, sampling_rate=TARGET_SAMPLE_RATE):
    """Energy-thresholded VAD: keep the voiced span plus a small padding."""
    waveform = np.asarray(waveform, dtype=np.float32)
    frame = int(sampling_rate * VAD_FRAME_MS / 1000.0)
    hop = int(sampling_rate * VAD_HOP_MS / 1000.0)

    if len(waveform) < frame:
        return waveform

    rms = np.zeros(1 + (len(waveform) - frame) // hop, dtype=np.float32)
    for i, start in enumerate(range(0, len(waveform) - frame + 1, hop)):
        rms[i] = np.sqrt(np.mean(waveform[start:start + frame] ** 2) + 1e-12)

    voiced = (20.0 * np.log10(rms + 1e-12)) > VAD_DB_THRESHOLD

    if not np.any(voiced):
        return waveform

    idx = np.where(voiced)[0]
    start_ms = int(idx[0] * hop)
    end_ms = int(idx[-1] * hop + frame)
    pad = int(sampling_rate * VAD_MIN_PAD_S)

    return waveform[max(0, start_ms - pad):min(len(waveform), end_ms + pad)]


def peak_normalize(waveform, target_db=DBFS_LEVEL):
    """Peak-normalize the signal to 'target_db' dBFS (e.g. -1.0 dBFS)."""
    waveform = np.asarray(waveform, dtype=np.float32)
    peak = np.max(np.abs(waveform))
    if peak <= 1e-12:
        return waveform
    gain = 10.0 ** (target_db / 20.0)
    return waveform * (gain / peak)


import re

chars_to_ignore_regex = r'[\,\?\.\!\-\;\:\"]'

def prepare_dataset(batch):
    audio = batch["audio"]

    # Stage 1: VAD trim + peak normalization to -1.0 dBFS
    waveform = np.asarray(audio["array"], dtype=np.float32)
    waveform = vad_trim(waveform, sampling_rate=audio["sampling_rate"])
    waveform = peak_normalize(waveform, DBFS_LEVEL)

    batch["input_values"] = processor(
        waveform,
        sampling_rate=audio["sampling_rate"]
    ).input_values[0]

    cleaned_text = re.sub(
        chars_to_ignore_regex,
        "",
        batch["text"]
    ).upper()

    batch["labels"] = processor.tokenizer(
        cleaned_text
    ).input_ids

    return batch


train_dataset = train_dataset.map(
    prepare_dataset,
    remove_columns=["audio", "text", "participant"]
)

print(train_dataset)

from sklearn.model_selection import train_test_split

# Split participants, not individual audio samples
train_participants, val_participants = train_test_split(
    filtered_participants,
    test_size=2,
    random_state=42
)

train_participants = sorted(train_participants, key=int)
val_participants = sorted(val_participants, key=int)

print("Train participants:", train_participants)
print("Validation participants:", val_participants)

train_data = []
val_data = []

for participant in filtered_participants:
    audio_path = os.path.join(data_root, participant, "audio")

    for filename in os.listdir(audio_path):
        if not filename.endswith(".wav"):
            continue

        parts = filename.replace(".wav", "").split("_")

        if len(parts) >= 4 and parts[1] == "BCS":
            item = {
                "audio": os.path.join(audio_path, filename),
                "text": parts[3],
                "participant": participant
            }

            if participant in train_participants:
                train_data.append(item)
            elif participant in val_participants:
                val_data.append(item)

print("Training samples:", len(train_data))
print("Validation samples:", len(val_data))

from datasets import Dataset, Audio

train_dataset = Dataset.from_list(train_data)
val_dataset = Dataset.from_list(val_data)

train_dataset = train_dataset.cast_column(
    "audio",
    Audio(sampling_rate=TARGET_SAMPLE_RATE)
)

val_dataset = val_dataset.cast_column(
    "audio",
    Audio(sampling_rate=TARGET_SAMPLE_RATE)
)

print("Train:", train_dataset)
print("Validation:", val_dataset)

# ===== Stage 2 (b) + (c): stochastic augmentation in the data collator =====
# Manuscript: augmentations are applied DYNAMICALLY DURING BATCH TRAINING -
# not cached at map()-time - so I apply them in the collator, which runs on
# every batch:
#   - pitch-shift each clip by a random n_steps in [-3.0, +4.0] semitones,
#     keeping the duration unchanged (librosa phase vocoder).
#   - mix in an ambient-noise segment at a random SNR in [0, 15] dB.
# Set NOISE_DIR to a folder of real ambient clips if available; otherwise a
# small synthetic colored-noise bank is generated so the pipeline still runs.
NOISE_DIR = None  # e.g. "/content/drive/MyDrive/datasets/noise" (optional)
AUGMENT_PROB = 0.8
PITCH_SEMITONES = (-3.0, 4.0)
SNR_DB_RANGE = (0.0, 15.0)


def _synthetic_noise_bank(sample_rate=TARGET_SAMPLE_RATE,
                          n_segments=5, seconds=5.0):
    rng = np.random.default_rng(0)
    bank = []
    for _ in range(n_segments):
        white = rng.standard_normal(int(sample_rate * seconds)).astype(np.float32)
        brown = np.cumsum(white, dtype=np.float32)
        brown = brown - np.mean(brown)
        denom = np.std(brown) + 1e-12
        bank.append((0.35 * white + 0.65 * (brown / denom)).astype(np.float32))
    return bank


from dataclasses import dataclass
from typing import Dict, List, Optional, Union
import torch
from transformers import TrainerCallback

@dataclass
class DataCollatorCTCWithPadding:
    processor: object
    padding: Union[bool, str] = True
    augment: bool = False
    sample_rate: int = TARGET_SAMPLE_RATE
    augment_prob: float = AUGMENT_PROB
    pitch_semitones: tuple = PITCH_SEMITONES
    snr_db: tuple = SNR_DB_RANGE
    noise_dir: Optional[str] = NOISE_DIR

    def __post_init__(self):
        self._noise_bank = None

    def _load_noise_bank(self):
        if self._noise_bank is None:
            if self.noise_dir and os.path.isdir(self.noise_dir):
                clips = []
                for filename in sorted(os.listdir(self.noise_dir)):
                    if not filename.lower().endswith((".wav", ".flac", ".ogg", ".mp3")):
                        continue
                    try:
                        clip, sr = sf.read(
                            os.path.join(self.noise_dir, filename),
                            dtype="float32"
                        )
                        if sr != self.sample_rate:
                            clip = librosa.resample(
                                clip, orig_sr=sr, target_sr=self.sample_rate
                            ).astype(np.float32)
                        clips.append(clip)
                    except Exception:
                        continue
                self._noise_bank = clips if clips else _synthetic_noise_bank(self.sample_rate)
            else:
                self._noise_bank = _synthetic_noise_bank(self.sample_rate)
        return self._noise_bank

    def _apply_pitch_shift(self, waveform):
        n_steps = float(np.random.uniform(*self.pitch_semitones))
        if abs(n_steps) < 0.1:
            return waveform
        return librosa.effects.pitch_shift(
            waveform, sr=self.sample_rate, n_steps=n_steps
        ).astype(np.float32)

    def _apply_noise_mix(self, waveform):
        bank = self._load_noise_bank()
        clip = bank[np.random.randint(0, len(bank))]

        n = len(waveform)
        if len(clip) < n:
            start = 0
            clip = np.resize(clip, n)
        else:
            start = np.random.randint(0, len(clip) - n + 1)
        segment = clip[start:start + n]

        sig_power = np.mean(waveform ** 2) + 1e-12
        noise_power = np.mean(segment ** 2) + 1e-12
        snr_db = float(np.random.uniform(*self.snr_db))  # positive = signal louder
        target_noise_power = sig_power / (10.0 ** (snr_db / 10.0))
        scale = np.sqrt(target_noise_power / noise_power)

        return (waveform + scale * segment).astype(np.float32)

    def __call__(self, features: List[Dict]) -> Dict[str, torch.Tensor]:
        input_features = [
            {"input_values": feature["input_values"]}
            for feature in features
        ]

        label_features = [
            {"input_ids": feature["labels"]}
            for feature in features
        ]

        batch = self.processor.feature_extractor.pad(
            input_features,
            padding=self.padding,
            return_attention_mask=True,
            return_tensors="pt"
        )

        labels_batch = self.processor.tokenizer.pad(
            label_features,
            padding=self.padding,
            return_tensors="pt"
        )

        attention_mask = batch.pop("attention_mask", None)

        # Stochastic domain adaptation, recomputed on every training batch.
        if self.augment:
            values = batch["input_values"]
            for i in range(values.shape[0]):
                length = int(attention_mask[i].sum().item())
                if length <= 0:
                    continue
                waveform = values[i, :length].numpy().astype(np.float32)

                if np.random.random() < self.augment_prob:
                    waveform = self._apply_pitch_shift(waveform)
                if np.random.random() < self.augment_prob:
                    waveform = self._apply_noise_mix(waveform)

                values[i, :length] = torch.from_numpy(waveform)

        labels = labels_batch["input_ids"].masked_fill(
            labels_batch.attention_mask.ne(1),
            -100
        )

        batch["labels"] = labels

        return batch


data_collator = DataCollatorCTCWithPadding(
    processor=processor,
    padding=True
)


def _set_augmentation(state):
    """Enable the full augmentation pipeline for training; disable it for
    evaluation so WER/PER benchmarks measure the model, not the noise."""
    data_collator.augment = state
    model.config.apply_spec_augment = state


class ToggleAugmentationCallback(TrainerCallback):
    def on_train_begin(self, args, state, control, **kwargs):
        _set_augmentation(True)

    def on_eval_begin(self, args, state, control, **kwargs):
        _set_augmentation(False)


print("Data collator ready!")

from transformers import TrainingArguments
import torch

training_args = TrainingArguments(
    output_dir="./hubert-bcs",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    dataloader_num_workers=2,
    learning_rate=1e-4,
    warmup_steps=50,
    num_train_epochs=50,
    fp16=torch.cuda.is_available(),
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    remove_unused_columns=False,
    torch_compile=False,
    gradient_checkpointing=False,
    save_total_limit=1,
)

# Prepare both train and validation datasets
columns_expected = ["audio", "text", "participant"]

# Check if columns still exist in train_dataset before mapping
if all(col in train_dataset.column_names for col in columns_expected):
    train_dataset = train_dataset.map(
        prepare_dataset,
        remove_columns=columns_expected
    )
else:
    print("train_dataset already processed (columns 'audio', 'text', 'participant' not found). Skipping map.")

# Check if columns still exist in val_dataset before mapping
if all(col in val_dataset.column_names for col in columns_expected):
    val_dataset = val_dataset.map(
        prepare_dataset,
        remove_columns=columns_expected
    )
else:
    print("val_dataset already processed (columns 'audio', 'text', 'participant' not found). Skipping map.")

print(train_dataset)
print(val_dataset)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    callbacks=[ToggleAugmentationCallback()],
)

print("Trainer ready!")

trainer.train()

# Persist the best checkpoint (already loaded into trainer.model, since
# load_best_model_at_end=True) plus the processor, so it can be downloaded
# from Colab and pointed to by the EchoVoice backend's ECHOVOICE_MODEL_DIR.
trainer.save_model("./hubert-bcs")
processor.save_pretrained("./hubert-bcs")
print("Saved fine-tuned checkpoint + processor to ./hubert-bcs")

!pip install -q g2p_en

import nltk
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("cmudict")

import evaluate
import torch
import re
from g2p_en import G2p

wer_metric = evaluate.load("wer")
g2p = G2p()


def text_to_phonemes(text):
    phonemes = g2p(text)

    phonemes = [
        p for p in phonemes
        if p.strip() and not re.match(r"^[.,!?;:'\"]$", p)
    ]

    phonemes = [re.sub(r"\d", "", p) for p in phonemes]

    return phonemes


def phoneme_error_rate(reference, prediction):
    ref = text_to_phonemes(reference)
    hyp = text_to_phonemes(prediction)

    dp = [[0] * (len(hyp) + 1) for _ in range(len(ref) + 1)]

    for i in range(len(ref) + 1):
        dp[i][0] = i

    for j in range(len(hyp) + 1):
        dp[0][j] = j

    for i in range(1, len(ref) + 1):
        for j in range(1, len(hyp) + 1):
            if ref[i - 1] == hyp[j - 1]:
                cost = 0
            else:
                cost = 1

            dp[i][j] = min(
                dp[i - 1][j] + 1,
                dp[i][j - 1] + 1,
                dp[i - 1][j - 1] + cost
            )

    if len(ref) == 0:
        return 0.0 if len(hyp) == 0 else 1.0

    return dp[-1][-1] / len(ref)


# Benchmark on clean data: make sure augmentation is fully disabled so WER/PER
# measure the acoustic model, not the training-time noise/perturbations.
_set_augmentation(False)

pred_output = trainer.predict(val_dataset)

pred_logits = pred_output.predictions
pred_ids = torch.argmax(torch.tensor(pred_logits), dim=-1)

pred_str = processor.batch_decode(pred_ids)

label_ids = pred_output.label_ids.copy()
label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

label_str = processor.batch_decode(
    label_ids,
    group_tokens=False
)


overall_wer = wer_metric.compute(
    predictions=pred_str,
    references=label_str
)

per_values = [
    phoneme_error_rate(ref, pred)
    for ref, pred in zip(label_str, pred_str)
]

overall_per = sum(per_values) / len(per_values)


print(f"\n\nOverall WER: {overall_wer:.4f} ({overall_wer * 100:.2f}%)")
print(f"Overall PER: {overall_per:.4f} ({overall_per * 100:.2f}%)")


for i, (reference, prediction, sample_per) in enumerate(
    zip(label_str, pred_str, per_values)
):

    sample_wer = wer_metric.compute(
        predictions=[prediction],
        references=[reference]
    )

    print()
    print(f"Sample {i + 1}")
    print(f"Reference : {reference}")
    print(f"Prediction: {prediction}")
    print(f"WER       : {sample_wer:.4f} ({sample_wer * 100:.2f}%)")
    print(f"PER       : {sample_per:.4f} ({sample_per * 100:.2f}%)")
    print(f"Ref phones: {' '.join(text_to_phonemes(reference))}")
    print(f"Pred phones: {' '.join(text_to_phonemes(prediction))}")